name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: b39b5c91-e3e9-418a-8bf0-abde606e5aab
          region: Australia East
          template: ./arm-templates/resource-group.json
          parameters: 
            location="Australia East"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: b39b5c91-e3e9-418a-8bf0-abde606e5aab
          template: ./arm-templates/storage-account.json
          parameters: 
            ./arm-templates/storage-account.parameters.json
            sku=Standard_LRS
            storageAccountName=pluralsightstorage002
            location="Australia East"
          deploymentMode: incremental
        
      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}
  